services:
  backend:
    build: ./backend
    container_name: ai-chat-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
      - ./.env.pg
    volumes:
      - ./backend:/app
    networks:
      - ai-chat
  
  db:
    image: pgvector/pgvector:pg16-trixie
    container_name: ai-chat-db
    ports:
      - 5432:5432
    env_file:
      - ./.env.pg
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - pgadmin
      - ai-chat


networks:
  pgadmin:
    external: true
  ai-chat:
    driver: bridge
